version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: api-iso-4217
        container_name: api-iso-4217
        ports:
            - "8000:8000"
        volumes:
            - ./:/var/www/html
        depends_on:
            - mysql
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: iso_4217
            DB_USERNAME: root
            DB_PASSWORD: root
    nginx:
        image: nginx:alpine
        container_name: my_nginx-api-iso-4217
        volumes:
          - ./:/var/www/html
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
         - "8002:80"
         - "443:443"
        depends_on:
          - app
    mysql:
        image: mysql:5.7
        container_name: mysql-db-api-iso-4217
        restart: always
        environment:
            MYSQL_DATABASE: iso_4217
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
        volumes:
            - mysql-data:/var/lib/mysql
        ports:
         - "3306:3306"
    redis:
        image: redis:latest
        ports:
        - "6379:6379"

volumes:
    mysql-data: